### ISSUE TITLE
line_width in config is no longer working

### ISSUE THREAD

**Issue by slmg** [PyCQA/isort#1465]
Hi,

Let me raise this as I could not find anything in relation to `line_width` deprecation in the changelog.

I am using the following config:
```ini
[settings]

line_width = 88
force_grid_wrap = 0
use_parentheses = true
multi_line_output = 3
include_trailing_comma = true
```
I can tell it worked in version `4.3.21`. From at least `5.4.2` onward, the following error is returned when running the below:

```sh
> isort **/*.py --check-only
Traceback (most recent call last):
  File "/home/moby/.local/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/home/moby/.local/lib/python3.8/site-packages/isort/main.py", line 830, in main
    config = Config(**config_dict)
  File "/home/moby/.local/lib/python3.8/site-packages/isort/settings.py", line 426, in __init__
    super().__init__(sources=tuple(sources), **combined_config)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'line_width'
```
Changing `line_width = 88` to `line_length = 88` in the config works.

Thanks

**Comment by timothycrosley** [comment]
@slmg, 

Thanks for the report!

Did a quick check to confirm: `line_width` was never supported within an isort config file, though it would be an easy mistake to make since it was the name of CLI flag `--line-width`. However, isort < 5 simply wouldn't error out when any invalid config option was provided, ignoring them instead. This led to a lot of broken configs so the behavior was adjusted in 5.0.0 to ensure all invalid configurations would fail fast.

~Timothy
